[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "Amina Patel"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "click",
      "target": "e3"
    },
    "to": "s002",
    "notes": [
      "postcondition 1: passed - url contains \"#/updates\""
    ]
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e4"
    },
    "to": "s003",
    "notes": []
  },
  {
    "from": "s003",
    "action": {
      "type": "click",
      "target": "e5"
    },
    "to": "s004",
    "notes": [
      "postcondition 1: passed - url contains \"#/check-answers\"",
      "postcondition 2: passed - text present \"No\""
    ]
  },
  {
    "from": "s004",
    "action": {
      "type": "click",
      "target": "e4"
    },
    "to": "s005",
    "notes": [
      "postcondition 1: passed - url contains \"#/updates\""
    ]
  },
  {
    "from": "s005",
    "action": {
      "type": "click",
      "target": "e3"
    },
    "to": "s006",
    "notes": []
  },
  {
    "from": "s006",
    "action": {
      "type": "type",
      "target": "e5",
      "text": "changed@example.com"
    },
    "to": "s007",
    "notes": []
  },
  {
    "from": "s007",
    "action": {
      "type": "click",
      "target": "e6"
    },
    "to": "s008",
    "notes": [
      "postcondition 1: passed - url contains \"#/check-answers\"",
      "postcondition 2: passed - text present \"changed@example.com\""
    ]
  }
]
