- navigation:
  - link "pretix.de":
    - /url: /control/
    - img
    - text: pretix.de
  - list:
    - listitem:
      - link " Go to shop":
        - /url: /nexui/nexui-event/
  - list:
    - listitem:
      - button " Admin mode"
    - listitem:
      - link " admin@localhost":
        - /url: /control/settings
    - listitem:
      - link "":
        - /url: /control/logout
  - navigation:
    - link "  NExUI Benchmark Event Mon, June 15, 2026":
      - /url: "#"
    - list:
      - listitem:
        - link " TEST MODE":
          - /url: /control/event/nexui/nexui-event/live/
      - listitem:
        - link " Dashboard":
          - /url: /control/event/nexui/nexui-event/
      - listitem:
        - link " Settings":
          - /url: /control/event/nexui/nexui-event/settings/
        - link "":
          - /url: "#"
      - listitem:
        - link " Products":
          - /url: /control/event/nexui/nexui-event/items/
        - link "":
          - /url: "#"
        - list:
          - listitem:
            - link "Products":
              - /url: /control/event/nexui/nexui-event/items/
          - listitem:
            - link "Quotas":
              - /url: /control/event/nexui/nexui-event/quotas/
          - listitem:
            - link "Categories":
              - /url: /control/event/nexui/nexui-event/categories/
          - listitem:
            - link "Questions":
              - /url: /control/event/nexui/nexui-event/questions/
          - listitem:
            - link "Discounts":
              - /url: /control/event/nexui/nexui-event/discounts/
      - listitem:
        - link " Orders":
          - /url: /control/event/nexui/nexui-event/orders/
        - link "":
          - /url: "#"
      - listitem:
        - link " Vouchers":
          - /url: /control/event/nexui/nexui-event/vouchers/
        - link "":
          - /url: "#"
      - listitem:
        - link " Check-in":
          - /url: /control/event/nexui/nexui-event/checkinlists/
        - link "":
          - /url: "#"
      - listitem:
        - link " Send out emails":
          - /url: /control/event/nexui/nexui-event/sendmail/
        - link "":
          - /url: "#"
- link "Starting with version 1.2.0, pretix automatically checks for updates in the background. During this check, anonymous data is transmitted to servers operated by pretix' developers. Click on this message to find out more, disable this feature or enter your email address to get notified via email if a new update arrives. This message will disappear once you clicked it.":
  - /url: /control/global/update/
- link "Click here to do a license compliance check to make sure your usage of pretix is in line with pretix' license.":
  - /url: /control/global/license/
- text: The cronjob component of pretix was not executed in the last hours. Please check that you have completed all installation steps and your cronjob is executed correctly.
- 'heading "Modify product: General Admission" [level=1]'
- list:
  - listitem:
    - tab "General"
  - listitem:
    - tab "Price" [expanded]
  - listitem:
    - tab "Availability"
  - listitem:
    - tab "Add-ons"
  - listitem:
    - tab "Bundled products"
  - listitem:
    - tab "Program times"
  - listitem:
    - tab "Tickets & Badges"
  - listitem:
    - tab "Check-in & Validity"
  - listitem:
    - tab "Additional settings"
- group:
  - text: Default price
  - textbox "Default price": "25.00"
  - text: USD If this product has multiple variations, you can set different prices for each of the variations. If a variation does not have a special price or if you do not have variations, this price will be used. Sales tax Optional
  - combobox "Sales tax Optional":
    - option "---------" [selected]
  - checkbox "Free price input"
  - text: Free price input If this option is active, your users can choose the price themselves. The price configured above is then interpreted as the minimum price a user has to enter. You could use this e.g. to collect additional donations for your event. Original price Optional
  - textbox "Original price Optional": "30.00"
  - text: USD If set, this will be displayed next to the current price to show that the current price is a discounted one. This is just a cosmetic setting and will not actually impact pricing.
- button "Save"
- heading "Product history" [level=3]
- list:
  - listitem:
    - paragraph:  2026-06-01 21:58  admin@localhost
    - paragraph: The product has been created.
- contentinfo:
  - text:  Times displayed in UTC ·
  - link "ticketing powered by pretix":
    - /url: /redirect/?url=https%3A//pretix.eu%3AAHe5H-yJEY2h25VMrXKQDJCYKUTAk1BevTl2kBFIduI