from __future__ import annotations

import html
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import quote

import imageio.v2 as imageio
import numpy as np
from PIL import Image, ImageDraw, ImageFont

from nexui.io import NexUIError
from nexui.task import TaskPackage, load_task


BACKGROUND = "#f4f1ea"
HEADER_BG = "#1d3557"
HEADER_FG = "#f8f9fa"
PANEL_BG = "#fffdf8"
PANEL_BORDER = "#d6d0c3"
TEXT = "#222222"
MUTED = "#5c6770"
ACCENT = "#e76f51"
SUCCESS = "#2a9d8f"
WARNING = "#b08900"
ERROR = "#c1121f"
HIGHLIGHT = "#f4a261"


@dataclass(frozen=True)
class ReplayVideoOptions:
    output_path: Path
    fps: int = 1
    seconds_per_scene: float = 2.0
    max_width: int = 1600


@dataclass(frozen=True)
class ReplayReportOptions:
    output_path: Path
    video_path: Path | None = None


def resolve_task_for_replay(trace: dict[str, Any], task_path: str | Path | None = None) -> TaskPackage:
    if task_path is not None:
        return load_task(task_path)

    task_info = trace.get("task")
    if isinstance(task_info, dict) and task_info.get("root"):
        return load_task(Path(task_info["root"]))

    raise NexUIError(
        "Replay video generation requires a task package. "
        "Pass --task or use a trace generated by a newer nexui run command."
    )


def render_trace_video(task: TaskPackage, trace: dict[str, Any], options: ReplayVideoOptions) -> dict[str, Any]:
    if options.fps <= 0:
        raise NexUIError("--fps must be greater than 0")
    if options.seconds_per_scene <= 0:
        raise NexUIError("--seconds-per-scene must be greater than 0")

    frames_per_scene = max(int(round(options.fps * options.seconds_per_scene)), 1)
    options.output_path.parent.mkdir(parents=True, exist_ok=True)

    first_screenshot = _load_snapshot_image(task, trace["initial_snapshot"])
    canvas_size = _compute_canvas_size(first_screenshot.size, options.max_width)

    writer_kwargs: dict[str, Any] = {"fps": options.fps}
    if options.output_path.suffix.lower() != ".gif":
        writer_kwargs["ffmpeg_log_level"] = "error"

    with imageio.get_writer(str(options.output_path), **writer_kwargs) as writer:
        intro = _render_intro_frame(task, trace, canvas_size)
        _append_frame(writer, intro, frames_per_scene)

        for step in trace["steps"]:
            before = _render_step_frame(task, trace, step, canvas_size, scene="before")
            _append_frame(writer, before, frames_per_scene)
            after = _render_step_frame(task, trace, step, canvas_size, scene="after")
            _append_frame(writer, after, frames_per_scene)

        outro = _render_outro_frame(task, trace, canvas_size)
        _append_frame(writer, outro, frames_per_scene)

    return {
        "video_path": str(options.output_path.resolve()),
        "frame_count": (len(trace["steps"]) * 2 + 2) * frames_per_scene,
        "fps": options.fps,
        "seconds_per_scene": options.seconds_per_scene,
    }


def render_trace_report(
    task: TaskPackage,
    trace: dict[str, Any],
    options: ReplayReportOptions,
    *,
    score: dict[str, Any] | None = None,
) -> dict[str, Any]:
    options.output_path.parent.mkdir(parents=True, exist_ok=True)
    video_uri = _relative_media_uri(options.video_path, options.output_path) if options.video_path else None
    html_text = _build_report_html(task, trace, video_uri=video_uri, video_path=options.video_path, score=score)
    options.output_path.write_text(html_text, encoding="utf-8")
    return {
        "report_path": str(options.output_path.resolve()),
        "has_embedded_video": bool(video_uri),
    }


def _append_frame(writer: Any, frame: Image.Image, count: int) -> None:
    payload = frame.convert("RGB")
    for _ in range(count):
        writer.append_data(np.asarray(payload))


def _compute_canvas_size(screenshot_size: tuple[int, int], max_width: int) -> tuple[int, int]:
    screenshot_width, screenshot_height = screenshot_size
    header_height = 90
    footer_padding = 40
    panel_width = max(420, min(520, int(screenshot_width * 0.35)))
    scale = 1.0
    total_width = screenshot_width + panel_width + 60
    if total_width > max_width:
        scale = max_width / total_width
    scaled_screenshot_width = max(int(screenshot_width * scale), 1)
    scaled_screenshot_height = max(int(screenshot_height * scale), 1)
    scaled_panel_width = max(int(panel_width * scale), 320)
    width = scaled_screenshot_width + scaled_panel_width + 60
    height = max(scaled_screenshot_height + header_height + footer_padding, 760)
    return (_round_up_to_multiple(width, 16), _round_up_to_multiple(height, 16))


def _relative_media_uri(media_path: Path, report_path: Path) -> str:
    relative_path = os.path.relpath(media_path.resolve(), report_path.parent.resolve())
    return quote(relative_path.replace(os.sep, "/"))


def _round_up_to_multiple(value: int, base: int) -> int:
    remainder = value % base
    if remainder == 0:
        return value
    return value + (base - remainder)


def _render_intro_frame(task: TaskPackage, trace: dict[str, Any], canvas_size: tuple[int, int]) -> Image.Image:
    initial = _load_snapshot_image(task, trace["initial_snapshot"])
    frame = _base_frame(canvas_size)
    _draw_header(frame, task.manifest["title"], f"Run {trace['run_id'][:8]} | Intro")
    screenshot_box = _paste_screenshot(frame, initial)
    panel_box = _panel_box(frame.size)
    draw = ImageDraw.Draw(frame)
    title_font = _font(28)
    body_font = _font(20)
    small_font = _font(16)
    _draw_wrapped(
        draw,
        panel_box,
        [
            ("Goal", task.manifest["goal"], title_font, TEXT),
            ("Instruction", task.instruction.strip(), body_font, TEXT),
            (
                "Start",
                f"Snapshot {trace['initial_snapshot']} | {trace['task_id']} | {trace['result']['status']}",
                small_font,
                MUTED,
            ),
        ],
    )
    _annotate_screenshot_label(draw, screenshot_box, "Initial page")
    return frame


def _render_step_frame(
    task: TaskPackage,
    trace: dict[str, Any],
    step: dict[str, Any],
    canvas_size: tuple[int, int],
    scene: str,
) -> Image.Image:
    if scene not in {"before", "after"}:
        raise NexUIError(f"Unknown replay scene: {scene}")

    snapshot_id = step["before_snapshot"] if scene == "before" else (step["after_snapshot"] or step["before_snapshot"])
    frame = _base_frame(canvas_size)
    action = step["submission"]["action"]
    explanation = step["submission"]["explanation"]
    snapshot = _load_snapshot_image(task, snapshot_id)
    screenshot_box = _paste_screenshot(frame, snapshot)
    draw = ImageDraw.Draw(frame)

    phase = "Before action" if scene == "before" else "After action"
    _draw_header(
        frame,
        task.manifest["title"],
        f"Step {step['step_index'] + 1} | {phase} | {action['type']}",
    )
    _annotate_screenshot_label(draw, screenshot_box, f"{snapshot_id} | {phase}")

    if scene == "before":
        _highlight_target(task, draw, screenshot_box, step["before_snapshot"], action)

    panel_box = _panel_box(frame.size)
    title_font = _font(24)
    body_font = _font(20)
    small_font = _font(16)
    status_text, status_color = _validation_style(step["validation"]["status"])
    details = [
        ("Action", _describe_action(task, step["before_snapshot"], action), title_font, TEXT),
        ("Explanation", explanation, body_font, TEXT),
        ("Validation", status_text, body_font, status_color),
        ("Safety", _format_safety(step.get("safety_flags", [])), small_font, _safety_color(step.get("safety_flags", []))),
        ("Notes", _format_notes(step.get("notes", [])), small_font, MUTED),
    ]
    if scene == "after" and action["type"] == "finish":
        details.append(("Final summary", trace["result"].get("final_summary", ""), body_font, TEXT))
    _draw_wrapped(draw, panel_box, details)
    return frame


def _render_outro_frame(task: TaskPackage, trace: dict[str, Any], canvas_size: tuple[int, int]) -> Image.Image:
    final_snapshot = _resolve_final_snapshot(trace)
    snapshot = _load_snapshot_image(task, final_snapshot)
    frame = _base_frame(canvas_size)
    _draw_header(frame, task.manifest["title"], f"Run {trace['run_id'][:8]} | Final result")
    screenshot_box = _paste_screenshot(frame, snapshot)
    draw = ImageDraw.Draw(frame)
    _annotate_screenshot_label(draw, screenshot_box, f"{final_snapshot} | Final state")
    panel_box = _panel_box(frame.size)
    title_font = _font(26)
    body_font = _font(20)
    small_font = _font(16)
    result = trace["result"]
    details = [
        ("Status", result["status"], title_font, _result_color(result["status"])),
        ("Task success", str(result.get("task_success", False)).lower(), body_font, TEXT),
        ("Termination", result.get("termination_reason", ""), small_font, MUTED),
        ("Final summary", result.get("final_summary", ""), body_font, TEXT),
    ]
    _draw_wrapped(draw, panel_box, details)
    return frame


def _base_frame(canvas_size: tuple[int, int]) -> Image.Image:
    return Image.new("RGBA", canvas_size, BACKGROUND)


def _draw_header(frame: Image.Image, title: str, subtitle: str) -> None:
    draw = ImageDraw.Draw(frame)
    width, _height = frame.size
    draw.rectangle([0, 0, width, 90], fill=HEADER_BG)
    draw.text((24, 20), title, font=_font(30), fill=HEADER_FG)
    draw.text((24, 56), subtitle, font=_font(16), fill="#dfe7ef")


def _paste_screenshot(frame: Image.Image, screenshot: Image.Image) -> tuple[int, int, int, int]:
    canvas_width, canvas_height = frame.size
    header_height = 90
    left_margin = 24
    right_panel_left = _panel_box(frame.size)[0]
    max_width = right_panel_left - left_margin - 24
    max_height = canvas_height - header_height - 24
    image = screenshot.convert("RGBA")
    image.thumbnail((max_width, max_height))
    top = header_height + 16 + max((max_height - image.height) // 2, 0)
    frame.alpha_composite(image, dest=(left_margin, top))
    return (left_margin, top, left_margin + image.width, top + image.height)


def _panel_box(canvas_size: tuple[int, int]) -> tuple[int, int, int, int]:
    width, height = canvas_size
    panel_width = min(max(360, int(width * 0.3)), 460)
    return (width - panel_width - 24, 110, width - 24, height - 24)


def _draw_wrapped(
    draw: ImageDraw.ImageDraw,
    panel_box: tuple[int, int, int, int],
    sections: list[tuple[str, str, ImageFont.FreeTypeFont | ImageFont.ImageFont, str]],
) -> None:
    left, top, right, bottom = panel_box
    draw.rounded_rectangle(panel_box, radius=18, fill=PANEL_BG, outline=PANEL_BORDER, width=2)
    cursor_y = top + 20
    inner_width = right - left - 28
    label_font = _font(14)
    for label, text, font, color in sections:
        if cursor_y >= bottom - 40:
            break
        draw.text((left + 14, cursor_y), label.upper(), font=label_font, fill=MUTED)
        cursor_y += 22
        wrapped = _wrap_text(draw, text or "None", font, inner_width)
        draw.multiline_text((left + 14, cursor_y), wrapped, font=font, fill=color, spacing=6)
        bbox = draw.multiline_textbbox((left + 14, cursor_y), wrapped, font=font, spacing=6)
        cursor_y = bbox[3] + 18


def _wrap_text(
    draw: ImageDraw.ImageDraw,
    text: str,
    font: ImageFont.FreeTypeFont | ImageFont.ImageFont,
    width: int,
) -> str:
    if not text.strip():
        return ""
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    for word in words:
        trial = " ".join(current + [word])
        trial_width = draw.textbbox((0, 0), trial, font=font)[2]
        if trial_width <= width or not current:
            current.append(word)
            continue
        lines.append(" ".join(current))
        current = [word]
    if current:
        lines.append(" ".join(current))
    return "\n".join(lines)


def _annotate_screenshot_label(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], text: str) -> None:
    x0, y0, _x1, _y1 = box
    padding = 8
    font = _font(14)
    bbox = draw.textbbox((0, 0), text, font=font)
    label_box = (x0, y0 - (bbox[3] - bbox[1]) - 18, x0 + (bbox[2] - bbox[0]) + 16, y0 - 6)
    draw.rounded_rectangle(label_box, radius=10, fill=HEADER_BG)
    draw.text((label_box[0] + padding, label_box[1] + 5), text, font=font, fill=HEADER_FG)


def _highlight_target(
    task: TaskPackage,
    draw: ImageDraw.ImageDraw,
    screenshot_box: tuple[int, int, int, int],
    snapshot_id: str,
    action: dict[str, Any],
) -> None:
    target_ref = action.get("target")
    if not target_ref:
        return
    candidates = task.build_observation(snapshot_id).get("candidates", [])
    candidate = next((item for item in candidates if item.get("ref") == target_ref), None)
    if not candidate:
        return
    bounds = candidate.get("bounds") or {}
    x = bounds.get("x")
    y = bounds.get("y")
    width = bounds.get("width")
    height = bounds.get("height")
    if not all(isinstance(value, (int, float)) for value in [x, y, width, height]):
        return
    if width <= 1 or height <= 1 or x < 0 or y < 0:
        return
    screenshot_left, screenshot_top, screenshot_right, screenshot_bottom = screenshot_box
    screenshot_width = screenshot_right - screenshot_left
    screenshot_height = screenshot_bottom - screenshot_top
    viewport = task.build_observation(snapshot_id)["viewport"]
    scale_x = screenshot_width / max(viewport["width"], 1)
    scale_y = screenshot_height / max(viewport["height"], 1)
    rect = [
        screenshot_left + (x * scale_x),
        screenshot_top + (y * scale_y),
        screenshot_left + ((x + width) * scale_x),
        screenshot_top + ((y + height) * scale_y),
    ]
    draw.rounded_rectangle(rect, radius=8, outline=HIGHLIGHT, width=5)
    tag = f"{target_ref} {candidate.get('role', '')}".strip()
    font = _font(14)
    text_box = draw.textbbox((0, 0), tag, font=font)
    label_rect = [
        rect[0],
        max(rect[1] - 28, screenshot_top),
        rect[0] + (text_box[2] - text_box[0]) + 16,
        max(rect[1] - 28, screenshot_top) + 24,
    ]
    draw.rounded_rectangle(label_rect, radius=8, fill=HIGHLIGHT)
    draw.text((label_rect[0] + 8, label_rect[1] + 4), tag, font=font, fill=TEXT)


def _load_snapshot_image(task: TaskPackage, snapshot_id: str) -> Image.Image:
    path = task.snapshot_dir(snapshot_id) / "screenshot.png"
    if not path.exists():
        raise NexUIError(f"Missing screenshot for replay: {path}")
    return Image.open(path)


def _describe_action(task: TaskPackage, snapshot_id: str, action: dict[str, Any]) -> str:
    action_type = action["type"]
    target_ref = action.get("target")
    target_desc = ""
    if target_ref:
        candidates = task.build_observation(snapshot_id).get("candidates", [])
        candidate = next((item for item in candidates if item.get("ref") == target_ref), None)
        if candidate:
            role = candidate.get("role") or candidate.get("tag") or "element"
            name = candidate.get("name") or candidate.get("text") or target_ref
            target_desc = f"{target_ref} ({role}: {name})"
        else:
            target_desc = target_ref

    if action_type == "click":
        return f"Click {target_desc or 'target'}"
    if action_type == "select":
        return f"Select {action.get('option', '')} on {target_desc or 'target'}"
    if action_type == "type":
        return f"Type into {target_desc or 'target'}: {action.get('text', '')}"
    if action_type == "press":
        return f"Press {action.get('key', '')}"
    if action_type == "finish":
        return "Finish the task"
    if action_type == "ask_user":
        return f"Ask user: {action.get('question', '')}"
    return f"{action_type} {target_desc}".strip()


def _validation_style(status: str) -> tuple[str, str]:
    if status == "ok":
        return "ok", SUCCESS
    if status in {"blocked_by_policy", "invalid_target"}:
        return status, WARNING
    return status, ERROR


def _format_notes(notes: list[str]) -> str:
    if not notes:
        return "None"
    return " ".join(notes)


def _format_safety(flags: list[str]) -> str:
    if not flags:
        return "None"
    return " | ".join(flags)


def _safety_color(flags: list[str]) -> str:
    if any(flag.startswith("critical:") for flag in flags):
        return ERROR
    if flags:
        return WARNING
    return MUTED


def _result_color(status: str) -> str:
    if status == "completed":
        return SUCCESS
    if status == "stopped":
        return WARNING
    return ERROR


def _resolve_final_snapshot(trace: dict[str, Any]) -> str:
    for step in reversed(trace["steps"]):
        if step.get("after_snapshot"):
            return step["after_snapshot"]
    return trace["initial_snapshot"]


def _font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for font_name in ["DejaVuSans.ttf", "Arial.ttf"]:
        try:
            return ImageFont.truetype(font_name, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def _build_report_html(
    task: TaskPackage,
    trace: dict[str, Any],
    *,
    video_uri: str | None,
    video_path: Path | None,
    score: dict[str, Any] | None,
) -> str:
    task_title = html.escape(task.manifest["title"])
    goal = html.escape(task.manifest["goal"])
    instruction = html.escape(task.instruction.strip())
    status = html.escape(trace["result"]["status"])
    final_summary = html.escape(trace["result"].get("final_summary", ""))
    termination = html.escape(trace["result"].get("termination_reason", ""))
    score_block = _score_report_html(score)
    steps_html = "\n".join(_step_report_html(task, step) for step in trace["steps"])
    raw_video_path = html.escape(str(video_path.resolve())) if video_path else ""
    raw_trace = html.escape(json.dumps(trace, indent=2))

    video_section = ""
    if video_uri:
        video_section = f"""
        <section class="card">
          <h2>Replay Video</h2>
          <video controls preload="metadata" src="{video_uri}"></video>
          <p class="hint">Raw video path: <code>{raw_video_path}</code></p>
          <p class="hint">Use the raw path above without any trailing <code>:1</code>. The <code>:1</code> suffix is a text line reference, not part of the filename.</p>
        </section>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{task_title} Replay Report</title>
  <style>
    :root {{
      --bg: #f4f1ea;
      --panel: #fffdf8;
      --ink: #1f2933;
      --muted: #52606d;
      --accent: #1d3557;
      --accent-2: #e76f51;
      --ok: #2a9d8f;
      --warn: #b08900;
      --bad: #c1121f;
      --border: #d6d0c3;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: "DejaVu Sans", Arial, sans-serif;
      background: linear-gradient(180deg, #ede7dc 0%, var(--bg) 100%);
      color: var(--ink);
      line-height: 1.45;
    }}
    header {{
      background: var(--accent);
      color: #f8f9fa;
      padding: 24px 28px;
    }}
    header h1 {{ margin: 0 0 8px; font-size: 30px; }}
    header p {{ margin: 4px 0; max-width: 960px; }}
    main {{
      max-width: 1180px;
      margin: 0 auto;
      padding: 24px;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 20px;
      margin-bottom: 20px;
    }}
    .card {{
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 18px;
      padding: 18px 20px;
      box-shadow: 0 10px 24px rgba(29, 53, 87, 0.08);
    }}
    h2 {{
      margin-top: 0;
      margin-bottom: 12px;
      font-size: 22px;
      color: var(--accent);
    }}
    dl {{
      display: grid;
      grid-template-columns: 180px 1fr;
      gap: 8px 12px;
      margin: 0;
    }}
    dt {{ font-weight: 700; color: var(--muted); }}
    dd {{ margin: 0; }}
    video {{
      width: 100%;
      border-radius: 12px;
      border: 1px solid var(--border);
      background: #000;
    }}
    .timeline {{
      display: grid;
      gap: 16px;
    }}
    .step {{
      border-left: 6px solid var(--accent-2);
    }}
    .step h3 {{
      margin: 0 0 10px;
      font-size: 19px;
    }}
    .pill {{
      display: inline-block;
      padding: 4px 8px;
      border-radius: 999px;
      font-size: 13px;
      font-weight: 700;
      margin-right: 8px;
      background: #ece8df;
      color: var(--ink);
    }}
    .ok {{ color: var(--ok); }}
    .warn {{ color: var(--warn); }}
    .bad {{ color: var(--bad); }}
    .hint {{
      color: var(--muted);
      font-size: 14px;
      margin: 10px 0 0;
    }}
    code, pre {{
      font-family: "DejaVu Sans Mono", "SFMono-Regular", Consolas, monospace;
    }}
    pre {{
      white-space: pre-wrap;
      overflow-wrap: anywhere;
      background: #f7f4ee;
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 14px;
      max-height: 460px;
      overflow: auto;
    }}
    details summary {{
      cursor: pointer;
      font-weight: 700;
      color: var(--accent);
    }}
    ul {{
      margin: 8px 0 0;
      padding-left: 20px;
    }}
  </style>
</head>
<body>
  <header>
    <h1>{task_title}</h1>
    <p><strong>Task ID:</strong> {html.escape(trace["task_id"])} | <strong>Run:</strong> {html.escape(trace["run_id"])}</p>
    <p><strong>Goal:</strong> {goal}</p>
    <p><strong>Instruction:</strong> {instruction}</p>
  </header>
  <main>
    <section class="grid">
      <div class="card">
        <h2>Run Summary</h2>
        <dl>
          <dt>Status</dt><dd>{status}</dd>
          <dt>Task success</dt><dd>{html.escape(str(trace["result"].get("task_success", False)).lower())}</dd>
          <dt>Termination</dt><dd>{termination or "None"}</dd>
          <dt>Initial snapshot</dt><dd>{html.escape(trace["initial_snapshot"])}</dd>
          <dt>Final summary</dt><dd>{final_summary or "None"}</dd>
        </dl>
      </div>
      {score_block}
    </section>
    {video_section}
    <section class="card">
      <h2>Step Timeline</h2>
      <div class="timeline">
        {steps_html}
      </div>
    </section>
    <section class="card">
      <details>
        <summary>Raw Trace JSON</summary>
        <pre>{raw_trace}</pre>
      </details>
    </section>
  </main>
</body>
</html>
"""


def _score_report_html(score: dict[str, Any] | None) -> str:
    if not score:
        return """
        <div class="card">
          <h2>Score</h2>
          <p class="hint">No score data was attached to this report.</p>
        </div>
        """
    metrics = score.get("metrics", {})
    passed = html.escape(str(score.get("passed", False)).lower())
    explanation_mode = html.escape(str(score.get("explanation_mode", "")))
    return f"""
    <div class="card">
      <h2>Score</h2>
      <dl>
        <dt>Passed</dt><dd>{passed}</dd>
        <dt>Explanation mode</dt><dd>{explanation_mode}</dd>
        <dt>Step efficiency</dt><dd>{html.escape(str(metrics.get("step_efficiency", "")))}</dd>
        <dt>Invalid actions</dt><dd>{html.escape(str(metrics.get("invalid_action_count", "")))}</dd>
        <dt>Explanation truthfulness</dt><dd>{html.escape(str(metrics.get("explanation_truthfulness", "")))}</dd>
        <dt>Explanation usefulness</dt><dd>{html.escape(str(metrics.get("explanation_usefulness", "")))}</dd>
        <dt>Structured coverage</dt><dd>{html.escape(str(metrics.get("explanation_structured_coverage", "")))}</dd>
        <dt>Action alignment</dt><dd>{html.escape(str(metrics.get("explanation_action_alignment", "")))}</dd>
        <dt>Pre-state grounding</dt><dd>{html.escape(str(metrics.get("explanation_pre_state_grounding", "")))}</dd>
        <dt>Goal linkage</dt><dd>{html.escape(str(metrics.get("explanation_goal_linkage", "")))}</dd>
        <dt>Post-state faithfulness</dt><dd>{html.escape(str(metrics.get("explanation_post_state_faithfulness", "")))}</dd>
        <dt>Safety calibration</dt><dd>{html.escape(str(metrics.get("explanation_safety_calibration", "")))}</dd>
        <dt>Conciseness</dt><dd>{html.escape(str(metrics.get("explanation_conciseness", "")))}</dd>
        <dt>Explanation overall</dt><dd>{html.escape(str(metrics.get("explanation_overall", "")))}</dd>
        <dt>Final summary quality</dt><dd>{html.escape(str(metrics.get("final_summary_quality", "")))}</dd>
      </dl>
    </div>
    """


def _step_report_html(task: TaskPackage, step: dict[str, Any]) -> str:
    action = step["submission"]["action"]
    explanation = html.escape(step["submission"].get("explanation", ""))
    validation_status = step["validation"]["status"]
    validation_class = "ok" if validation_status == "ok" else ("warn" if validation_status in {"blocked_by_policy", "invalid_target"} else "bad")
    notes_html = _list_html(step.get("notes", []))
    safety_html = _list_html(step.get("safety_flags", []))
    action_text = html.escape(_describe_action(task, step["before_snapshot"], action))
    before_snapshot = html.escape(step["before_snapshot"])
    after_snapshot = html.escape(step.get("after_snapshot") or "None")
    return f"""
    <article class="card step">
      <h3>Step {step["step_index"] + 1}</h3>
      <p><span class="pill">{html.escape(action["type"])}</span><strong>{action_text}</strong></p>
      <dl>
        <dt>Before snapshot</dt><dd>{before_snapshot}</dd>
        <dt>After snapshot</dt><dd>{after_snapshot}</dd>
        <dt>Validation</dt><dd class="{validation_class}">{html.escape(validation_status)}</dd>
        <dt>Explanation</dt><dd>{explanation or "None"}</dd>
        <dt>Notes</dt><dd>{notes_html}</dd>
        <dt>Safety flags</dt><dd>{safety_html}</dd>
      </dl>
    </article>
    """


def _list_html(items: list[str]) -> str:
    if not items:
        return "None"
    rendered = "".join(f"<li>{html.escape(item)}</li>" for item in items)
    return f"<ul>{rendered}</ul>"
