[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e11",
      "text": "Cierra"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - field value equals \"Cierra\"",
      "postcondition 2: passed - text present \"Cierra Vega 39 cierra@example.com 10000 Insurance\""
    ]
  }
]
