[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e8"
    },
    "to": "s001",
    "notes": [
      "dialog: confirm - Do you confirm action?",
      "postcondition 1: passed - text present \"You selected Ok\""
    ]
  }
]
