- main:
  - img
  - heading "Sign in" [level=1]
  - text: Username
  - textbox "Username": Heath93
  - text: Password
  - textbox "Password": s3cret
  - checkbox "Remember me"
  - text: Remember me
  - button "Sign In"
  - link "Don't have an account? Sign Up":
    - /url: /signup
  - paragraph:
    - text: Built by
    - link:
      - /url: https://cypress.io
      - img