[
  {
    "from": "s000",
    "action": {
      "type": "focus",
      "target": "e1"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "press",
      "key": "Enter"
    },
    "to": "s002",
    "notes": []
  }
]
