[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "nexui_admin"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "NExUIAdmin!2026"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e3"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - url contains \"/web/index.php/pim/contactDetails/empNumber/1\"",
      "postcondition 2: passed - text present \"Heading level 6: Contact Details\""
    ]
  }
]
