- paragraph:
  - link "Skip to inaccessible demo page":
    - /url: "#page"
- paragraph:
  - link "W3C logo":
    - /url: https://www.w3.org/
    - img "W3C logo"
  - link "Web Accessibility Initiative (WAI) logo":
    - /url: https://www.w3.org/WAI/
    - img "Web Accessibility Initiative (WAI) logo"
- heading "Inaccessible Tickets Page - Before and After Demonstration" [level=1]
- paragraph: Improving a Web site using Web Content Accessibility Guidelines (WCAG) 2.0
- list:
  - listitem:
    - link "Overview":
      - /url: ../Overview.html
  - listitem:
    - link "Home":
      - /url: home.html
  - listitem:
    - link "News":
      - /url: news.html
  - listitem:
    - text: "Current location: Tickets"
    - list:
      - listitem:
        - strong: "Inaccessible:"
        - text: Inaccessible Tickets Page
        - link "Inaccessible Tickets Page Report":
          - /url: ./reports/tickets.html
      - listitem:
        - strong: "Accessible:"
        - link "Accessible Tickets Page":
          - /url: ../after/tickets.html
        - link "Accessible Tickets Page Report":
          - /url: ../after/reports/tickets.html
    - link "Show Annotations":
      - /url: ./annotated/tickets.html
  - listitem:
    - link "Survey":
      - /url: survey.html
  - listitem:
    - link "Template":
      - /url: template.html
- paragraph: Demo starts here
- table:
  - rowgroup:
    - row:
      - cell:
        - table:
          - rowgroup:
            - row:
              - cell:
                - img
              - cell:
                - img
              - cell:
                - img
            - row:
              - cell:
                - img
              - cell:
                - table:
                  - rowgroup:
                    - row "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner. QUICKMENU ---->":
                      - cell "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner.":
                        - link "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner.":
                          - /url: home.html
                          - img "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner."
                      - cell:
                        - img
                      - cell:
                        - img
                      - cell:
                        - img
                      - cell "QUICKMENU ---->":
                        - combobox:
                          - option "QUICKMENU ---->" [selected]
                          - option "Broadcasting"
                          - option "Education"
                          - option "Electricity"
                          - option "Fire service"
                          - option "Gas service"
                          - option "Health care"
                          - option "Police service"
                          - option "Public Libraries"
                          - option "Social services"
                          - option "Social housing"
                          - option "Telecommunications"
                          - option "Town planning"
                          - option "Transportation"
                          - option "Waste management"
                          - option "Water services"
                    - row:
                      - cell:
                        - img
                    - 'row "Traffic: Construction work on Main Road Today: Wednesday 27 May 2026, Sunny, 23°C"':
                      - 'cell "Traffic: Construction work on Main Road Today: Wednesday 27 May 2026, Sunny, 23°C"':
                        - table:
                          - rowgroup:
                            - 'row "Traffic: Construction work on Main Road Today: Wednesday 27 May 2026, Sunny, 23°C"':
                              - 'cell "Traffic: Construction work on Main Road"'
                              - 'cell "Today: Wednesday 27 May 2026, Sunny, 23°C"'
                    - row:
                      - cell:
                        - img
                    - row:
                      - cell
                - table:
                  - rowgroup:
                    - row:
                      - cell:
                        - table:
                          - rowgroup:
                            - row:
                              - cell:
                                - img
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='home.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='news.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='tickets.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='survey.html';
                                  - img
                            - row:
                              - cell:
                                - img
                      - cell:
                        - img
                      - cell:
                        - paragraph:
                          - img
                        - table:
                          - rowgroup:
                            - 'row "Citylights in partnership with globo enterprises are proud to offer specially priced tickets to see these great artists - Les Garçons & The Obelisks These special deals are exclusive to Citylights and can only be purchased by calling the ticket hotline: concert dates Les Garçons The Obelisks 12/2/06 24/3/06"':
                              - cell "Citylights in partnership with globo enterprises are proud to offer specially priced tickets to see these great artists - Les Garçons & The Obelisks These special deals are exclusive to Citylights and can only be purchased by calling the ticket hotline:":
                                - paragraph: Citylights in partnership with globo enterprises are proud to offer specially priced tickets to see these great artists - Les Garçons & The Obelisks
                                - paragraph: "These special deals are exclusive to Citylights and can only be purchased by calling the ticket hotline:"
                              - cell "concert dates Les Garçons The Obelisks 12/2/06 24/3/06":
                                - text: concert dates
                                - table:
                                  - rowgroup:
                                    - row "Les Garçons The Obelisks":
                                      - cell "Les Garçons"
                                      - cell "The Obelisks"
                                    - row "12/2/06 24/3/06":
                                      - cell "12/2/06"
                                      - cell "24/3/06"
                            - 'row "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!: music line phone number"':
                              - 'cell "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!: music line phone number"':
                                - table:
                                  - rowgroup:
                                    - 'row "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!: music line phone number"':
                                      - cell "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!:"
                                      - cell "music line phone number":
                                        - img "music line phone number"
                        - paragraph
                        - table:
                          - rowgroup:
                            - row:
                              - img
                        - table:
                          - rowgroup:
                            - row "ADULT FS RS DC ST":
                              - cell "ADULT"
                              - cell "FS"
                              - cell "RS"
                              - cell "DC"
                              - cell "ST"
                            - row "Obelisks - Monkey, Monkey $20.90 $20.90 $20.90 $20.90":
                              - cell "Obelisks - Monkey, Monkey"
                              - cell "$20.90"
                              - cell "$20.90"
                              - cell "$20.90"
                              - cell "$20.90"
                            - row "Les Garçons de la Plage $20.90 $27.90 $30.90 $33.90":
                              - cell "Les Garçons de la Plage"
                              - cell "$20.90"
                              - cell "$27.90"
                              - cell "$30.90"
                              - cell "$33.90"
                            - row "Concession":
                              - cell "Concession"
                            - row "Obelisks - Monkey, Monkey $20.90 $20.90 $20.90 $20.90":
                              - cell "Obelisks - Monkey, Monkey"
                              - cell "$20.90"
                              - cell "$20.90"
                              - cell "$20.90"
                              - cell "$20.90"
                            - row "Les Garçons de la Plage $20.90 $27.90 $30.90 $33.90":
                              - cell "Les Garçons de la Plage"
                              - cell "$20.90"
                              - cell "$27.90"
                              - cell "$30.90"
                              - cell "$33.90"
                            - row "Group (5 or more)":
                              - cell "Group (5 or more)"
                            - row "Obelisks - Monkey, Monkey $14.90 $14.90 $14.90 $14.90":
                              - cell "Obelisks - Monkey, Monkey"
                              - cell "$14.90"
                              - cell "$14.90"
                              - cell "$14.90"
                              - cell "$14.90"
                            - row "Les Garçons de la Plage $14.90 $20.90 $22.90 $23.90":
                              - cell "Les Garçons de la Plage"
                              - cell "$14.90"
                              - cell "$20.90"
                              - cell "$22.90"
                              - cell "$23.90"
                        - table:
                          - rowgroup:
                            - 'row "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!: music line phone number"':
                              - 'cell "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!: music line phone number"':
                                - table:
                                  - rowgroup:
                                    - 'row "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!: music line phone number"':
                                      - cell "Buy tickets by phoning the M-u-s-i-c line ---- get your tickets now!:"
                                      - cell "music line phone number":
                                        - img "music line phone number"
                            - row:
                              - cell:
                                - text: Citylights Terms and Conditions
                                - paragraph: "[1] YOU AGREE THROUGH THE ACT OF CALLING THE M-U-S-I-C LINE OR BY READING ANY PART OF THESE TERMS AND CONDITIONS THAT YOU WILL NOT, NOW OR EVER, (A) TRANSMIT ANY MATERIAL TO ANY PERSON, LIVING OR DEAD, THAT MAY BE DEEMED BY THAT PERSON TO BE DEFAMATORY, HARMFUL, UNLAWFUL, ARGUMENTATIVE OR CONFUSING, AND THAT FURTHERMORE (B) ANY RESEMBLANCE BETWEEN YOURSELF OR YOUR FAMILY AND ANY PERSONS, VEGETABLES OR MUSICAL INSTRUMENTS LIVING, DEAD OR OTHER FEATURED ON THE CITYLIGHTS WEBSITE IS ENTIRELY UNINTENTIONAL AND THAT WHERE SUCH A RESEMBLANCE MAY OCCUR THAT YOU WILL TAKE IMMEDIATE ACTION TO PREVENT SUCH RESEMBLANCE REOCCURRING. [2] CITYLIGHTS SHALL NOT BE LIABLE TO YOU FOR ANY DAMAGES OR LOSS OF REVENUE, GOODWILL, ENTHUSIASM OR SKIN TONE ARISING OUT OF OR IN CONNECTION WITH ANY USE OR OTHER INTERACTION WITH (A) THE CITYLIGHTS WEBSITES, (B) REVIEWS OF THE CITYLIGHTS WEBSITE, (C) ANY EMPLOYEES OR POTENTIAL EMPLOYEES OF CITYLIGHTS PAST OR PRESENT OR (D) ANY WEBSITE LINKING TO OR LINKED FROM THE CITYLIGHTS WEBSITE, WHETHER DIRECTLY OR THROUGH OTHER WEBSITES. [3] REMEDIES. SINCE CITYLIGHTS WOULD BE IRREPARABLY DAMAGED TO AN UNFORESEEABLE DEGREE IF SECTIONS [1] AND [2] WERE NOT SPECIFICALLY ENFORCED, CITYLIGHTS WILL BE ENTITLED WITHOUT BOND, OTHER SECURITY OR PROOF OF DAMAGES, TO APPROPRIATE EQUITABLE REMEDIES WITH RESPECT TO BREACHES OF SUCH SECTIONS, IN ADDITION TO ANY OTHER AVAILABLE REMEDIES."
                        - paragraph
                - table:
                  - rowgroup:
                    - row "Copyright © 2012 W3C® (MIT, ERCIM, Keio)":
                      - cell "Copyright © 2012 W3C® (MIT, ERCIM, Keio)":
                        - link "Copyright":
                          - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
                        - text: © 2012
                        - link "W3C":
                          - /url: https://www.w3.org/
                        - superscript: ®
                        - text: (
                        - link "MIT":
                          - /url: http://www.csail.mit.edu/
                        - text: ","
                        - link "ERCIM":
                          - /url: http://www.ercim.org/
                        - text: ","
                        - link "Keio":
                          - /url: http://www.keio.ac.jp/
                        - text: )
              - cell:
                - img
            - row:
              - cell:
                - img
              - cell:
                - img
              - cell:
                - img
- separator
- paragraph:
  - strong: "Status:"
  - text: 20 February 2012 (see
  - link "changelog":
    - /url: ../changelog.html
  - text: ") Editors:"
  - link "Shadi Abou-Zahra":
    - /url: https://www.w3.org/People/shadi/
  - text: and the
  - link "Education and Outreach Working Group (EOWG)":
    - /url: https://www.w3.org/WAI/EO/
  - text: . Developed with support from
  - link "WAI-TIES":
    - /url: https://www.w3.org/WAI/TIES/
  - text: and
  - link "WAI-AGE":
    - /url: https://www.w3.org/WAI/WAI-AGE/
  - text: projects, co-funded by the European Commission IST Programme. [see
  - link "Acknowledgements":
    - /url: ../acks.html
  - text: "]"
- paragraph:
  - text: "["
  - link "WAI Site Map":
    - /url: https://www.w3.org/WAI/sitemap.html
  - text: "] ["
  - link "Help with WAI Website":
    - /url: https://www.w3.org/WAI/sitehelp.html
  - text: "] ["
  - link "Search":
    - /url: https://www.w3.org/WAI/search.php
  - text: "] ["
  - link "Contacting WAI":
    - /url: https://www.w3.org/WAI/contacts
  - text: "]"
  - strong:
    - text: Feedback welcome to
    - link "wai-eo-editors@w3.org":
      - /url: mailto:wai-eo-editors@w3.org
  - text: (a publicly archived list) or
  - link "wai@w3.org":
    - /url: mailto:wai@w3.org
  - text: (a WAI staff-only list).
- paragraph:
  - link "Copyright":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
  - text: © 2012
  - link "W3C":
    - /url: https://www.w3.org/
  - superscript: ®
  - text: (
  - link "MIT":
    - /url: http://www.csail.mit.edu/
  - text: ","
  - link "ERCIM":
    - /url: http://www.ercim.org/
  - text: ","
  - link "Keio":
    - /url: http://www.keio.ac.jp/
  - text: ), All Rights Reserved. W3C
  - link "liability":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer
  - text: ","
  - link "trademark":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks
  - text: ","
  - link "document use":
    - /url: https://www.w3.org/Consortium/Legal/copyright-documents
  - text: and
  - link "software licensing":
    - /url: https://www.w3.org/Consortium/Legal/copyright-software
  - text: rules apply. Your interactions with this site are in accordance with our
  - link "public":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Public
  - text: and
  - link "Member":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Members
  - text: privacy statements.