[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "invalid-user"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "invalid-password"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e3"
    },
    "to": "s003",
    "notes": []
  }
]
