- banner:
  - link:
    - /url: https://demoqa.com
    - img
- img
- text: Elements
- img
- img
- text: Forms
- img
- img
- text: Alerts, Frame & Windows
- img
- list:
  - listitem:
    - link "Browser Windows":
      - /url: /browser-windows
      - img
      - text: Browser Windows
  - listitem:
    - link "Alerts":
      - /url: /alerts
      - img
      - text: Alerts
  - listitem:
    - link "Frames":
      - /url: /frames
      - img
      - text: Frames
  - listitem:
    - link "Nested Frames":
      - /url: /nestedframes
      - img
      - text: Nested Frames
  - listitem:
    - link "Modal Dialogs":
      - /url: /modal-dialogs
      - img
      - text: Modal Dialogs
- img
- text: Widgets
- img
- img
- text: Interactions
- img
- img
- text: Book Store Application
- img
- heading "Alerts" [level=1]
- text: Click Button to see alert
- button "Click me"
- text: On button click, alert will appear after 5 seconds
- button "Click me"
- text: On button click, confirm box will appearYou selected Cancel
- button "Click me"
- text: On button click, prompt box will appear
- button "Click me"
- contentinfo: © 2013-2026 TOOLSQA.COM | ALL RIGHTS RESERVED.