- paragraph:
  - link "Skip to accessible demo page":
    - /url: "#page"
- paragraph:
  - link "W3C logo":
    - /url: https://www.w3.org/
    - img "W3C logo"
  - link "Web Accessibility Initiative (WAI) logo":
    - /url: https://www.w3.org/WAI/
    - img "Web Accessibility Initiative (WAI) logo"
- heading "Accessible News Page - Before and After Demonstration" [level=1]
- paragraph: Improving a Web site using Web Content Accessibility Guidelines (WCAG) 2.0
- list:
  - listitem:
    - link "Overview":
      - /url: ../Overview.html
  - listitem:
    - link "Home":
      - /url: home.html
  - listitem:
    - text: "Current location: News"
    - list:
      - listitem:
        - strong: "Inaccessible:"
        - link "Inaccessible News Page":
          - /url: ../before/news.html
        - link "Inaccessible News Page Report":
          - /url: ../before/reports/news.html
      - listitem:
        - strong: "Accessible:"
        - text: Accessible News Page
        - link "Accessible News Page Report":
          - /url: ./reports/news.html
    - link "Show Annotations":
      - /url: ./annotated/news.html
  - listitem:
    - link "Tickets":
      - /url: tickets.html
  - listitem:
    - link "Survey":
      - /url: survey.html
  - listitem:
    - link "Template":
      - /url: template.html
- paragraph: Demo starts here
- list:
  - listitem:
    - link "Skip to content (within demo page)":
      - /url: "#content"
  - listitem:
    - link "Skip to navigation (within demo page)":
      - /url: "#navtarget"
- 'link "Citylights: your access to the city."':
  - /url: home.html
  - 'img "Citylights: your access to the city."'
- img "Sunny Spells"
- text: "Explore Site by Topic:"
- combobox "Explore Site by Topic:":
  - option "Quick Menu" [selected]
  - option "Broadcasting"
  - option "Education"
  - option "Electricity"
  - option "Fire service"
  - option "Gas service"
  - option "Health care"
  - option "Police service"
  - option "Public Libraries"
  - option "Social services"
  - option "Social housing"
  - option "Telecommunications"
  - option "Town planning"
  - option "Transportation"
  - option "Waste management"
  - option "Water services"
- button "Go"
- paragraph:
  - strong: "Traffic:"
  - text: Construction work on Main Road
- paragraph:
  - strong: "Today:"
  - text: Thursday 28 May 2026, Sunny Spells, 23°C
- heading "Navigation menu:" [level=2]
- list:
  - listitem:
    - link "Home":
      - /url: home.html
  - listitem: News
  - listitem:
    - link "Tickets":
      - /url: tickets.html
  - listitem:
    - link "Survey":
      - /url: survey.html
- heading "Citylights News" [level=1]
- heading "Heat wave linked to temperatures" [level=2]
- paragraph: "After three years of effort city scientists now agree that the primary cause of the 2003 heatwave was hot air from our air conditioning units. The study cost the city taxpayer under 10 million dollars said Prof. Steve 'Call me Stephen' Wahoonie, of City University Public Expenditure on Science dept. We had five top statisticians working on it: one to write the grant proposal, one to do the mathematical modelling, two to collaborate on the research paper, and one to hire a student to do the job."
- heading "Tough Wahoonie" [level=3]
- paragraph:
  - text: We soon realized that we were seeing a rise in temperatures every time a heatwave occurred. Also, the more air conditioning used, the bigger the heatwave. We knew it couldn't just be a coincidence, the match was 100%. Air conditioning was driving temperatures up, which in turn resulted in a heatwave, the Prof. explained. It all comes from
  - link "the way that air conditioning works":
    - /url: ../offsite.html
  - text: . Air conditioners produce cold air to go into the room
  - emphasis: but also hot air that's ducted away to the outside
  - text: . We are recommending a new city ordinance restricting use of air conditioning to winter months, when the heat will come in useful.
- heading "Return To Sender" [level=3]
- paragraph: "When questioned whether their results would be affected if air conditioners were found to be used on cold days, Wahoonie responded: we had one guy in the lab whining those kinds of questions. 'Why are you doing this? Why are there all those discrepencies in the department accounts?', but it was after we had written up the results. We later found that he took 40% of his sick days on Mondays or Fridays. How convenient. Some people have no shame."
- heading "Air-Con Fact Finding Mission" [level=3]
- paragraph:
  - img "Mrs B. Wahoonie in front of a canyon"
  - text: Mrs B. Wahoonie investigates shipping hot air to Australia
- heading "Man Gets Nine Months in Violin Case" [level=2]
- paragraph:
  - text: As news of the conviction and sentencing of infamous violin thief Pasquale Ginkgo-Biloba reached city hall, Mayor Auberon 'Slim' Shadi stated that he was furious at the boring sentence handed down by the judge in the case, and is demanding a review of sentencing policy. This is not the first time that judges have come under fire for lenient sentencing in musical-instrument related cases. Last year's
  - link "trombone forgery debacle":
    - /url: ../offsite.html
  - text: also resulted in a formal rebuke from the Mayor.
- heading "Your Shout" [level=2]
- paragraph:
  - link "Clara F.'s website":
    - /url: ../offsite.html
    - img "Clara F.'s website"
  - text: Well I think the Mayor's getting all heated up about nothing. Remember that 15 months is pretty much a lifetime to someone like me. But hey, I'm just a baby, and can't even vote, so you can ignore my opinion. And I can tell you that I'm standing for mayor on a ticket of infant suffrage.
- paragraph:
  - strong:
    - link "Clara F., 15 months":
      - /url: ../offsite.html
    - text: ", via email"
- heading "Lack of Brains Hinders Research" [level=2]
- heading "Brain donations at city hospital (by month)" [level=3]
- 'img "Brain Donations for May: 13, June: 13, July: 12, August: 8, September: 7."'
- paragraph: There has been a significant drop in brain donations as a result of the successful 'Slow Traffic, Safe Streets' policy, say city doctors. Brain donations are essential said Dr. Liam Colluspid of Central Hospital, at a press conference yesterday. I must ask that the Mayor either dispenses with these road safety measures, or else that every concerned citizen should consider right now whether there are any brains they aren't making much use of at the moment, that they might like to drop off.
- paragraph:
  - link "Copyright":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
  - text: © 2012
  - link "W3C":
    - /url: https://www.w3.org/
  - superscript: ®
  - text: (
  - link "MIT":
    - /url: http://www.csail.mit.edu/
  - text: ","
  - link "ERCIM":
    - /url: http://www.ercim.org/
  - text: ","
  - link "Keio":
    - /url: http://www.keio.ac.jp/
  - text: )
- separator
- paragraph:
  - strong: "Status:"
  - text: 20 February 2012 (see
  - link "changelog":
    - /url: ../changelog.html
  - text: ") Editors:"
  - link "Shadi Abou-Zahra":
    - /url: https://www.w3.org/People/shadi/
  - text: and the
  - link "Education and Outreach Working Group (EOWG)":
    - /url: https://www.w3.org/WAI/EO/
  - text: . Developed with support from
  - link "WAI-TIES":
    - /url: https://www.w3.org/WAI/TIES/
  - text: and
  - link "WAI-AGE":
    - /url: https://www.w3.org/WAI/WAI-AGE/
  - text: projects, co-funded by the European Commission IST Programme. [see
  - link "Acknowledgements":
    - /url: ../acks.html
  - text: "]"
- paragraph:
  - text: "["
  - link "WAI Site Map":
    - /url: https://www.w3.org/WAI/sitemap.html
  - text: "] ["
  - link "Help with WAI Website":
    - /url: https://www.w3.org/WAI/sitehelp.html
  - text: "] ["
  - link "Search":
    - /url: https://www.w3.org/WAI/search.php
  - text: "] ["
  - link "Contacting WAI":
    - /url: https://www.w3.org/WAI/contacts
  - text: "]"
  - strong:
    - text: Feedback welcome to
    - link "wai-eo-editors@w3.org":
      - /url: mailto:wai-eo-editors@w3.org
  - text: (a publicly archived list) or
  - link "wai@w3.org":
    - /url: mailto:wai@w3.org
  - text: (a WAI staff-only list).
- paragraph:
  - link "Copyright":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
  - text: © 2012
  - link "W3C":
    - /url: https://www.w3.org/
  - superscript: ®
  - text: (
  - link "MIT":
    - /url: http://www.csail.mit.edu/
  - text: ","
  - link "ERCIM":
    - /url: http://www.ercim.org/
  - text: ","
  - link "Keio":
    - /url: http://www.keio.ac.jp/
  - text: ), All Rights Reserved. W3C
  - link "liability":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer
  - text: ","
  - link "trademark":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks
  - text: ","
  - link "document use":
    - /url: https://www.w3.org/Consortium/Legal/copyright-documents
  - text: and
  - link "software licensing":
    - /url: https://www.w3.org/Consortium/Legal/copyright-software
  - text: rules apply. Your interactions with this site are in accordance with our
  - link "public":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Public
  - text: and
  - link "Member":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Members
  - text: privacy statements.