[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e31"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - text present \"Share\"",
      "postcondition 2: passed - text present \"Geo URI\""
    ]
  }
]
