- main:
  - img
  - heading "Login to Frappe" [level=4]
  - form:
    - text: Email
    - textbox "Email":
      - /placeholder: jane@example.com
      - text: Administrator
    - img
    - text: Password
    - textbox "Password":
      - /placeholder: •••••
    - img
    - text: Show
    - paragraph:
      - link "Forgot Password?":
        - /url: "#forgot"
    - button "Login"
    - paragraph: or
    - link "Login with Email Link":
      - /url: "#login-with-email-link"