[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e9"
    },
    "to": "s001",
    "notes": [
      "dialog: prompt - Please enter your name",
      "postcondition 1: passed - text present \"You entered NExUI\""
    ]
  }
]
