- link:
  - /url: /control/login
  - img
- text: Email
- textbox "Email"
- text: Password
- textbox "Password"
- checkbox "Keep me logged in"
- text: Keep me logged in
- button "Log in"
- link "Lost password?":
  - /url: /control/forgot
- contentinfo:
  - link "ticketing powered by pretix":
    - /url: /redirect/?url=https%3A//pretix.eu%3AeuTro54DJwl5DGiV43laun1tVVNUnqO6hGViSZAJ4T0