- paragraph:
  - link "Skip to inaccessible demo page":
    - /url: "#page"
- paragraph:
  - link "W3C logo":
    - /url: https://www.w3.org/
    - img "W3C logo"
  - link "Web Accessibility Initiative (WAI) logo":
    - /url: https://www.w3.org/WAI/
    - img "Web Accessibility Initiative (WAI) logo"
- heading "Inaccessible Template Page - Before and After Demonstration" [level=1]
- paragraph: Improving a Web site using Web Content Accessibility Guidelines (WCAG) 2.0
- list:
  - listitem:
    - link "Overview":
      - /url: ../Overview.html
  - listitem:
    - link "Home":
      - /url: home.html
  - listitem:
    - link "News":
      - /url: news.html
  - listitem:
    - link "Tickets":
      - /url: tickets.html
  - listitem:
    - link "Survey":
      - /url: survey.html
  - listitem:
    - text: "Current location: Template"
    - list:
      - listitem:
        - strong: "Inaccessible:"
        - text: Inaccessible Template
        - link "Inaccessible Template Report":
          - /url: ./reports/template.html
      - listitem:
        - strong: "Accessible:"
        - link "Accessible Template":
          - /url: ../after/template.html
        - link "Accessible Template Report":
          - /url: ../after/reports/template.html
    - link "Show Annotations":
      - /url: ./annotated/template.html
- paragraph: Demo starts here
- table:
  - rowgroup:
    - 'row "Red dot with a white letter ''C'' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says ''CITYLIGHTS'' which is the name of this online portal. Finally, the slogan of the portal, ''your access to the city'', follows in a turquoise green handwriting style and with a slight slant across the top banner. QUICKMENU ----> Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C Template [CONTENT] [TITLE] [IMAGE] [INTRO] Read more... [TITLE] [IMAGE] [INTRO] Read more... Copyright © 2012 W3C® (MIT, ERCIM, Keio)"':
      - 'cell "Red dot with a white letter ''C'' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says ''CITYLIGHTS'' which is the name of this online portal. Finally, the slogan of the portal, ''your access to the city'', follows in a turquoise green handwriting style and with a slight slant across the top banner. QUICKMENU ----> Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C Template [CONTENT] [TITLE] [IMAGE] [INTRO] Read more... [TITLE] [IMAGE] [INTRO] Read more... Copyright © 2012 W3C® (MIT, ERCIM, Keio)"':
        - table:
          - rowgroup:
            - row:
              - cell:
                - img
              - cell:
                - img
              - cell:
                - img
            - 'row "Red dot with a white letter ''C'' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says ''CITYLIGHTS'' which is the name of this online portal. Finally, the slogan of the portal, ''your access to the city'', follows in a turquoise green handwriting style and with a slight slant across the top banner. QUICKMENU ----> Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C Template [CONTENT] [TITLE] [IMAGE] [INTRO] Read more... [TITLE] [IMAGE] [INTRO] Read more... Copyright © 2012 W3C® (MIT, ERCIM, Keio)"':
              - cell:
                - img
              - 'cell "Red dot with a white letter ''C'' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says ''CITYLIGHTS'' which is the name of this online portal. Finally, the slogan of the portal, ''your access to the city'', follows in a turquoise green handwriting style and with a slight slant across the top banner. QUICKMENU ----> Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C Template [CONTENT] [TITLE] [IMAGE] [INTRO] Read more... [TITLE] [IMAGE] [INTRO] Read more... Copyright © 2012 W3C® (MIT, ERCIM, Keio)"':
                - table:
                  - rowgroup:
                    - row "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner. QUICKMENU ---->":
                      - cell "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner.":
                        - link "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner.":
                          - /url: home.html
                          - img "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner."
                      - cell:
                        - img
                      - cell:
                        - img
                      - cell:
                        - img
                      - cell "QUICKMENU ---->":
                        - combobox:
                          - option "QUICKMENU ---->" [selected]
                          - option "Broadcasting"
                          - option "Education"
                          - option "Electricity"
                          - option "Fire service"
                          - option "Gas service"
                          - option "Health care"
                          - option "Police service"
                          - option "Public Libraries"
                          - option "Social services"
                          - option "Social housing"
                          - option "Telecommunications"
                          - option "Town planning"
                          - option "Transportation"
                          - option "Waste management"
                          - option "Water services"
                    - row:
                      - cell:
                        - img
                    - 'row "Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C"':
                      - 'cell "Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C"':
                        - table:
                          - rowgroup:
                            - 'row "Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C"':
                              - 'cell "Traffic: Construction work on Main Road"'
                              - 'cell "Today: Thursday 28 May 2026, Sunny, 23°C"'
                    - row:
                      - cell:
                        - img
                    - row:
                      - cell
                - table:
                  - rowgroup:
                    - row "Template [CONTENT] [TITLE] [IMAGE] [INTRO] Read more... [TITLE] [IMAGE] [INTRO] Read more...":
                      - cell:
                        - table:
                          - rowgroup:
                            - row:
                              - cell:
                                - img
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='home.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='news.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='tickets.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='survey.html';
                                  - img
                            - row:
                              - cell:
                                - img
                      - cell:
                        - img
                      - cell "Template [CONTENT]":
                        - paragraph: Template
                        - text: "[CONTENT]"
                      - cell:
                        - img
                      - cell "[TITLE] [IMAGE] [INTRO] Read more... [TITLE] [IMAGE] [INTRO] Read more...":
                        - table:
                          - rowgroup:
                            - row:
                              - cell:
                                - img
                              - cell:
                                - img
                            - row "[TITLE]":
                              - cell "[TITLE]"
                            - row "[IMAGE]":
                              - cell "[IMAGE]"
                            - row "[INTRO] Read more...":
                              - cell "[INTRO] Read more...":
                                - table:
                                  - rowgroup:
                                    - row "[INTRO] Read more...":
                                      - cell "[INTRO] Read more...":
                                        - text: "[INTRO]"
                                        - link "Read more...":
                                          - /url: info
                            - row:
                              - cell
                            - row:
                              - cell:
                                - img
                            - row "[TITLE]":
                              - cell "[TITLE]"
                            - row "[IMAGE]":
                              - cell "[IMAGE]"
                            - row "[INTRO] Read more...":
                              - cell "[INTRO] Read more...":
                                - table:
                                  - rowgroup:
                                    - row "[INTRO] Read more...":
                                      - cell "[INTRO] Read more...":
                                        - text: "[INTRO]"
                                        - link "Read more...":
                                          - /url: info
                - table:
                  - rowgroup:
                    - row "Copyright © 2012 W3C® (MIT, ERCIM, Keio)":
                      - cell "Copyright © 2012 W3C® (MIT, ERCIM, Keio)":
                        - link "Copyright":
                          - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
                        - text: © 2012
                        - link "W3C":
                          - /url: https://www.w3.org/
                        - superscript: ®
                        - text: (
                        - link "MIT":
                          - /url: http://www.csail.mit.edu/
                        - text: ","
                        - link "ERCIM":
                          - /url: http://www.ercim.org/
                        - text: ","
                        - link "Keio":
                          - /url: http://www.keio.ac.jp/
                        - text: )
              - cell:
                - img
            - row:
              - cell:
                - img
              - cell:
                - img
              - cell:
                - img
- separator
- paragraph:
  - strong: "Status:"
  - text: 20 February 2012 (see
  - link "changelog":
    - /url: ../changelog.html
  - text: ") Editors:"
  - link "Shadi Abou-Zahra":
    - /url: https://www.w3.org/People/shadi/
  - text: and the
  - link "Education and Outreach Working Group (EOWG)":
    - /url: https://www.w3.org/WAI/EO/
  - text: . Developed with support from
  - link "WAI-TIES":
    - /url: https://www.w3.org/WAI/TIES/
  - text: and
  - link "WAI-AGE":
    - /url: https://www.w3.org/WAI/WAI-AGE/
  - text: projects, co-funded by the European Commission IST Programme. [see
  - link "Acknowledgements":
    - /url: ../acks.html
  - text: "]"
- paragraph:
  - text: "["
  - link "WAI Site Map":
    - /url: https://www.w3.org/WAI/sitemap.html
  - text: "] ["
  - link "Help with WAI Website":
    - /url: https://www.w3.org/WAI/sitehelp.html
  - text: "] ["
  - link "Search":
    - /url: https://www.w3.org/WAI/search.php
  - text: "] ["
  - link "Contacting WAI":
    - /url: https://www.w3.org/WAI/contacts
  - text: "]"
  - strong:
    - text: Feedback welcome to
    - link "wai-eo-editors@w3.org":
      - /url: mailto:wai-eo-editors@w3.org
  - text: (a publicly archived list) or
  - link "wai@w3.org":
    - /url: mailto:wai@w3.org
  - text: (a WAI staff-only list).
- paragraph:
  - link "Copyright":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
  - text: © 2012
  - link "W3C":
    - /url: https://www.w3.org/
  - superscript: ®
  - text: (
  - link "MIT":
    - /url: http://www.csail.mit.edu/
  - text: ","
  - link "ERCIM":
    - /url: http://www.ercim.org/
  - text: ","
  - link "Keio":
    - /url: http://www.keio.ac.jp/
  - text: ), All Rights Reserved. W3C
  - link "liability":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer
  - text: ","
  - link "trademark":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks
  - text: ","
  - link "document use":
    - /url: https://www.w3.org/Consortium/Legal/copyright-documents
  - text: and
  - link "software licensing":
    - /url: https://www.w3.org/Consortium/Legal/copyright-software
  - text: rules apply. Your interactions with this site are in accordance with our
  - link "public":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Public
  - text: and
  - link "Member":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Members
  - text: privacy statements.