[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "nexui_admin"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "NExUIAdmin!2026"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e3"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - url contains \"/web/index.php/pim/contactDetails/empNumber/1\""
    ]
  },
  {
    "from": "s003",
    "action": {
      "type": "type",
      "target": "e39",
      "text": "456 Benchmark Ave"
    },
    "to": "s004",
    "notes": []
  },
  {
    "from": "s004",
    "action": {
      "type": "type",
      "target": "e49",
      "text": "nexui-admin+saved@example.test"
    },
    "to": "s005",
    "notes": []
  },
  {
    "from": "s005",
    "action": {
      "type": "click",
      "target": "e50"
    },
    "to": "s006",
    "notes": [
      "postcondition 1: passed - text present \"Successfully Updated\""
    ]
  }
]
