[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "nexui_admin"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "NExUIAdmin!2026"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e3"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - url contains \"/web/index.php/pim/viewEmployeeList\"",
      "postcondition 2: passed - text present \"Employee Information\""
    ]
  },
  {
    "from": "s003",
    "action": {
      "type": "type",
      "target": "e23",
      "text": "Ava"
    },
    "to": "s004",
    "notes": []
  },
  {
    "from": "s004",
    "action": {
      "type": "click",
      "target": "e31"
    },
    "to": "s005",
    "notes": [
      "postcondition 1: passed - field value equals \"Ava\"",
      "postcondition 2: passed - text absent \"Marcus Lee\""
    ]
  }
]
