- paragraph: Getting Started
- text: A Administrator admin@example.com
- banner
- list:
  - listitem:
    - link:
      - /url: /desk
  - listitem:
    - link "/ Supplier":
      - /url: /desk/supplier
  - listitem:
    - link "/ NExUI Test Supplier":
      - /url: /desk/supplier/NExUI%20Test%20Supplier
- text: Enabled
- button "View"
- button
- button
- button "Menu":
  - img
- button "Save"
- tablist:
  - listitem:
    - tab "Details"
  - listitem:
    - tab "Address & Contact"
  - listitem:
    - tab "Tax"
  - listitem:
    - tab "Accounting"
  - listitem:
    - tab "Settings"
  - listitem:
    - tab "Portal Users"
  - listitem:
    - tab "Connections"
- tabpanel "Details":
  - text: Supplier Type *
  - combobox:
    - option "Company" [selected]
    - option "Individual"
    - option "Partnership"
  - text: supplier_type Supplier Name *
  - textbox: NExUI Test Supplier
  - text: supplier_name Supplier Group
  - combobox
  - status: Begin typing for results.
  - text: supplier_group Country
  - combobox: United States
  - status: Begin typing for results.
  - text: country
  - checkbox "Is Transporter"
  - text: Is Transporter
  - paragraph
  - text: is_transporter Defaults Billing Currency
  - combobox
  - status: Begin typing for results.
  - text: default_currency Default Company Bank Account
  - combobox
  - status: Begin typing for results.
  - text: default_bank_account Price List
  - combobox
  - status: Begin typing for results.
  - text: default_price_list More Information
- text: Comments A comment Type a reply / comment
- paragraph
- heading "Activity" [level=4]
- button "New Email"
- button "New Event"
- text: You created this · 35 minutes ago You last edited this · 35 minutes ago
- button:
  - img
- text: NT
- button
- button
- img
- text: NExUI Test Supplier Assign
- button:
  - img
- text: Attachments
- button:
  - img
- text: Tags
- button:
  - img
- text: Share
- button:
  - img
- list:
  - listitem: Last Edited By You 35 minutes ago
  - listitem: Created By You 35 minutes ago
  - listitem
- contentinfo
- navigation:
  - img
  - text: May, 2026
  - img
- text: Su Mo Tu We Th Fr Sa 26 27 28 29 30 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 1 2 3 4 5 6 Today