[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "Heath93"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "s3cret"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e4"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - text present \"Account Balance\""
    ]
  },
  {
    "from": "s003",
    "action": {
      "type": "click",
      "target": "e3"
    },
    "to": "s004",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/transaction/new\""
    ]
  },
  {
    "from": "s004",
    "action": {
      "type": "type",
      "target": "e5",
      "text": "Darrel"
    },
    "to": "s005",
    "notes": []
  },
  {
    "from": "s005",
    "action": {
      "type": "click",
      "target": "e6"
    },
    "to": "s006",
    "notes": [
      "postcondition 1: passed - text present \"Darrel Ortiz\"",
      "postcondition 2: passed - candidate exists for {\"role\":\"button\",\"name\":\"Request\"}"
    ]
  },
  {
    "from": "s006",
    "action": {
      "type": "type",
      "target": "e5",
      "text": "24"
    },
    "to": "s007",
    "notes": []
  },
  {
    "from": "s007",
    "action": {
      "type": "type",
      "target": "e6",
      "text": "NExUI monstrous Darrel request"
    },
    "to": "s008",
    "notes": []
  },
  {
    "from": "s008",
    "action": {
      "type": "click",
      "target": "e7"
    },
    "to": "s009",
    "notes": [
      "postcondition 1: passed - candidate exists for {\"role\":\"link\",\"name\":\"Return To Transactions\"}"
    ]
  },
  {
    "from": "s009",
    "action": {
      "type": "click",
      "target": "e5"
    },
    "to": "s010",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/\""
    ]
  },
  {
    "from": "s010",
    "action": {
      "type": "click",
      "target": "e7"
    },
    "to": "s011",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/personal\"",
      "postcondition 2: passed - text present \"NExUI monstrous Darrel request\"",
      "postcondition 3: passed - text present \"Darrel Ortiz\"",
      "postcondition 4: passed - text present \"+$24.00\""
    ]
  },
  {
    "from": "s011",
    "action": {
      "type": "click",
      "target": "e17"
    },
    "to": "s012",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/transaction/\"",
      "postcondition 2: passed - text present \"Transaction Detail\"",
      "postcondition 3: passed - text present \"NExUI monstrous Darrel request\""
    ]
  },
  {
    "from": "s012",
    "action": {
      "type": "type",
      "target": "e6",
      "text": "NExUI monstrous Darrel follow-up"
    },
    "to": "s013",
    "notes": []
  },
  {
    "from": "s013",
    "action": {
      "type": "press",
      "key": "Enter"
    },
    "to": "s014",
    "notes": [
      "postcondition 1: passed - text present \"NExUI monstrous Darrel follow-up\""
    ]
  },
  {
    "from": "s014",
    "action": {
      "type": "click",
      "target": "e8"
    },
    "to": "s015",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/\""
    ]
  },
  {
    "from": "s015",
    "action": {
      "type": "click",
      "target": "e7"
    },
    "to": "s016",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/personal\"",
      "postcondition 2: passed - text present \"NExUI monstrous Darrel request\"",
      "postcondition 3: passed - text present \"0 1\""
    ]
  },
  {
    "from": "s016",
    "action": {
      "type": "click",
      "target": "e17"
    },
    "to": "s017",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/transaction/\"",
      "postcondition 2: passed - text present \"Transaction Detail\"",
      "postcondition 3: passed - text present \"NExUI monstrous Darrel follow-up\""
    ]
  }
]
