[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e37"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - url contains \"/admin/admin/user/edit/user_id/1/\"",
      "postcondition 2: passed - text present \"Heading level 1: Admin User\""
    ]
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e27",
      "text": "admin+nexui@example.test"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "type",
      "target": "e32",
      "text": "admin1234"
    },
    "to": "s003",
    "notes": []
  }
]
