[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e9",
      "text": "john"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e10",
      "text": "demo"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e11"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - url contains \"/overview.htm\"",
      "postcondition 2: passed - candidate exists for {\"role\":\"link\",\"name\":\"Find Transactions\"}"
    ]
  },
  {
    "from": "s003",
    "action": {
      "type": "click",
      "target": "e13"
    },
    "to": "s004",
    "notes": [
      "postcondition 1: passed - url contains \"/findtrans.htm\"",
      "postcondition 2: passed - text present \"Find Transactions\""
    ]
  }
]
