[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "Administrator"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "admin"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e4"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - url contains \"/desk/customer/new-customer-\"",
      "postcondition 2: passed - candidate exists for {\"role\":\"button\",\"name\":\"Save\"}"
    ]
  }
]
