[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e15"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - url contains \"/admin/admin/user/new/\"",
      "postcondition 2: passed - text present \"Heading level 1: New User\""
    ]
  },
  {
    "from": "s001",
    "action": {
      "type": "click",
      "target": "e19"
    },
    "to": "s002",
    "notes": [
      "postcondition 1: passed - text present \"Administrators\""
    ]
  }
]
