[
  {
    "from": "s000",
    "action": {
      "type": "wait"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "click",
      "target": "e13"
    },
    "to": "s002",
    "notes": [
      "postcondition 1: passed - text present \"Apple monitor 24\"",
      "postcondition 2: passed - text absent \"Samsung galaxy s6\""
    ]
  }
]
