- link:
  - /url: admin.htm;jsessionid=CFAE331853E509164B250DE07B52691F
  - img
- link "ParaBank":
  - /url: index.htm;jsessionid=CFAE331853E509164B250DE07B52691F
  - img "ParaBank"
- paragraph: Experience the difference
- list:
  - listitem: Solutions
  - listitem:
    - link "About Us":
      - /url: about.htm;jsessionid=CFAE331853E509164B250DE07B52691F
  - listitem:
    - link "Services":
      - /url: services.htm;jsessionid=CFAE331853E509164B250DE07B52691F
  - listitem:
    - link "Products":
      - /url: http://www.parasoft.com/jsp/products.jsp
  - listitem:
    - link "Locations":
      - /url: http://www.parasoft.com/jsp/pr/contacts.jsp
  - listitem:
    - link "Admin Page":
      - /url: admin.htm;jsessionid=CFAE331853E509164B250DE07B52691F
- list:
  - listitem:
    - link "home":
      - /url: index.htm;jsessionid=CFAE331853E509164B250DE07B52691F
  - listitem:
    - link "about":
      - /url: about.htm;jsessionid=CFAE331853E509164B250DE07B52691F
  - listitem:
    - link "contact":
      - /url: contact.htm;jsessionid=CFAE331853E509164B250DE07B52691F
- heading "Customer Login" [level=2]
- paragraph: Username
- textbox
- paragraph: Password
- textbox
- button "Log In"
- paragraph:
  - link "Forgot login info?":
    - /url: lookup.htm;jsessionid=CFAE331853E509164B250DE07B52691F
- paragraph:
  - link "Register":
    - /url: register.htm;jsessionid=CFAE331853E509164B250DE07B52691F
- heading "Signing up is easy!" [level=1]
- paragraph: If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.
- table:
  - rowgroup:
    - 'row "First Name: Nora"':
      - cell "First Name:"
      - cell "Nora":
        - textbox: Nora
      - cell
    - 'row "Last Name: Reed"':
      - cell "Last Name:"
      - cell "Reed":
        - textbox: Reed
      - cell
    - 'row "Address: 42 Cedar Street"':
      - cell "Address:"
      - cell "42 Cedar Street":
        - textbox: 42 Cedar Street
      - cell
    - 'row "City: Fargo"':
      - cell "City:"
      - cell "Fargo":
        - textbox: Fargo
      - cell
    - 'row "State: North Dakota"':
      - cell "State:"
      - cell "North Dakota":
        - textbox: North Dakota
      - cell
    - row "Zip Code:":
      - cell "Zip Code:"
      - cell:
        - textbox
      - cell
    - 'row "Phone #:"':
      - 'cell "Phone #:"'
      - cell:
        - textbox
      - cell
    - row "SSN:":
      - cell "SSN:"
      - cell:
        - textbox
      - cell
    - row:
      - cell
    - row "Username:":
      - cell "Username:"
      - cell:
        - textbox
      - cell
    - row "Password:":
      - cell "Password:"
      - cell:
        - textbox
      - cell
    - row "Confirm:":
      - cell "Confirm:"
      - cell:
        - textbox
      - cell
    - row "Register":
      - cell
      - cell "Register":
        - button "Register"
- list:
  - listitem:
    - link "Home":
      - /url: index.htm;jsessionid=CFAE331853E509164B250DE07B52691F
    - text: "|"
  - listitem:
    - link "About Us":
      - /url: about.htm;jsessionid=CFAE331853E509164B250DE07B52691F
    - text: "|"
  - listitem:
    - link "Services":
      - /url: services.htm;jsessionid=CFAE331853E509164B250DE07B52691F
    - text: "|"
  - listitem:
    - link "Products":
      - /url: http://www.parasoft.com/jsp/products.jsp
    - text: "|"
  - listitem:
    - link "Locations":
      - /url: http://www.parasoft.com/jsp/pr/contacts.jsp
    - text: "|"
  - listitem:
    - link "Forum":
      - /url: http://forums.parasoft.com/
    - text: "|"
  - listitem:
    - link "Site Map":
      - /url: sitemap.htm;jsessionid=CFAE331853E509164B250DE07B52691F
    - text: "|"
  - listitem:
    - link "Contact Us":
      - /url: contact.htm;jsessionid=CFAE331853E509164B250DE07B52691F
- paragraph: © Parasoft. All rights reserved.
- list:
  - listitem: "Visit us at:"
  - listitem:
    - link "www.parasoft.com":
      - /url: http://www.parasoft.com/