[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "Heath93"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "s3cret"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e4"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - text present \"Account Balance\""
    ]
  },
  {
    "from": "s003",
    "action": {
      "type": "click",
      "target": "e10"
    },
    "to": "s004",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/bankaccounts\""
    ]
  },
  {
    "from": "s004",
    "action": {
      "type": "click",
      "target": "e5"
    },
    "to": "s005",
    "notes": [
      "postcondition 1: passed - url contains \"http://localhost:3000/bankaccounts/new\"",
      "postcondition 2: passed - candidate exists for {\"role\":\"textbox\",\"name\":\"Bank Name\"}"
    ]
  }
]
