[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e18"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - modal state is \"dialog_open\""
    ]
  }
]
