[
  {
    "from": "s000",
    "action": {
      "type": "type",
      "target": "e1",
      "text": "Administrator"
    },
    "to": "s001",
    "notes": []
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e2",
      "text": "admin"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "click",
      "target": "e4"
    },
    "to": "s003",
    "notes": [
      "postcondition 1: passed - url contains \"/desk/customer/new-customer-\"",
      "postcondition 2: passed - candidate exists for {\"role\":\"button\",\"name\":\"Save\"}"
    ]
  },
  {
    "from": "s003",
    "action": {
      "type": "type",
      "target": "e14",
      "text": "NExUI Save Verify Customer"
    },
    "to": "s004",
    "notes": []
  },
  {
    "from": "s004",
    "action": {
      "type": "click",
      "target": "e5"
    },
    "to": "s005",
    "notes": []
  },
  {
    "from": "s005",
    "action": {
      "type": "click",
      "target": "e4"
    },
    "to": "s006",
    "notes": [
      "postcondition 1: passed - url contains \"/desk/customer/NExUI%20Save%20Verify%20Customer\""
    ]
  },
  {
    "from": "s006",
    "action": {
      "type": "click",
      "target": "e2"
    },
    "to": "s007",
    "notes": [
      "postcondition 1: passed - url contains \"/desk/customer\"",
      "postcondition 2: passed - candidate exists for {\"role\":\"textbox\",\"name\":\"Customer Name\"}"
    ]
  },
  {
    "from": "s007",
    "action": {
      "type": "type",
      "target": "e8",
      "text": "NExUI Save Verify Customer"
    },
    "to": "s008",
    "notes": []
  },
  {
    "from": "s008",
    "action": {
      "type": "click",
      "target": "e11"
    },
    "to": "s009",
    "notes": [
      "postcondition 1: passed - url contains \"/desk/customer?customer_name=\"",
      "postcondition 2: passed - field value equals \"NExUI Save Verify Customer\"",
      "postcondition 3: passed - text present \"NExUI Save Verify Customer\""
    ]
  }
]
