- paragraph:
  - link "Skip to inaccessible demo page":
    - /url: "#page"
- paragraph:
  - link "W3C logo":
    - /url: https://www.w3.org/
    - img "W3C logo"
  - link "Web Accessibility Initiative (WAI) logo":
    - /url: https://www.w3.org/WAI/
    - img "Web Accessibility Initiative (WAI) logo"
- heading "Inaccessible Home Page - Before and After Demonstration" [level=1]
- paragraph: Improving a Web site using Web Content Accessibility Guidelines (WCAG) 2.0
- list:
  - listitem:
    - link "Overview":
      - /url: ../Overview.html
  - listitem:
    - text: "Current location: Home"
    - list:
      - listitem:
        - strong: "Inaccessible:"
        - text: Inaccessible Home Page
        - link "Inaccessible Home Page Report":
          - /url: ./reports/home.html
      - listitem:
        - strong: "Accessible:"
        - link "Accessible Home Page":
          - /url: ../after/home.html
        - link "Accessible Home Page Report":
          - /url: ../after/reports/home.html
    - link "Show Annotations":
      - /url: ./annotated/home.html
  - listitem:
    - link "News":
      - /url: news.html
  - listitem:
    - link "Tickets":
      - /url: tickets.html
  - listitem:
    - link "Survey":
      - /url: survey.html
  - listitem:
    - link "Template":
      - /url: template.html
- paragraph: Demo starts here
- table:
  - rowgroup:
    - row:
      - cell:
        - table:
          - rowgroup:
            - row:
              - cell:
                - img
              - cell:
                - img
              - cell:
                - img
            - row:
              - cell:
                - img
              - cell:
                - table:
                  - rowgroup:
                    - row "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner. QUICKMENU ---->":
                      - cell "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner.":
                        - link "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner.":
                          - /url: home.html
                          - img "Red dot with a white letter 'C' that symbolizes a moon crescent as well as the sun. This logo is followed by a black banner that says 'CITYLIGHTS' which is the name of this online portal. Finally, the slogan of the portal, 'your access to the city', follows in a turquoise green handwriting style and with a slight slant across the top banner."
                      - cell:
                        - img
                      - cell:
                        - img
                      - cell:
                        - img
                      - cell "QUICKMENU ---->":
                        - combobox:
                          - option "QUICKMENU ---->" [selected]
                          - option "Broadcasting"
                          - option "Education"
                          - option "Electricity"
                          - option "Fire service"
                          - option "Gas service"
                          - option "Health care"
                          - option "Police service"
                          - option "Public Libraries"
                          - option "Social services"
                          - option "Social housing"
                          - option "Telecommunications"
                          - option "Town planning"
                          - option "Transportation"
                          - option "Waste management"
                          - option "Water services"
                    - row:
                      - cell:
                        - img
                    - 'row "Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C"':
                      - 'cell "Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C"':
                        - table:
                          - rowgroup:
                            - 'row "Traffic: Construction work on Main Road Today: Thursday 28 May 2026, Sunny, 23°C"':
                              - 'cell "Traffic: Construction work on Main Road"'
                              - 'cell "Today: Thursday 28 May 2026, Sunny, 23°C"'
                    - row:
                      - cell:
                        - img
                    - row:
                      - cell
                - table:
                  - rowgroup:
                    - row:
                      - cell:
                        - table:
                          - rowgroup:
                            - row:
                              - cell:
                                - img
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='home.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='news.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='tickets.html';
                                  - img
                            - row:
                              - cell:
                                - img
                            - row:
                              - cell:
                                - link:
                                  - /url: javascript:location.href='survey.html';
                                  - img
                            - row:
                              - cell:
                                - img
                      - cell:
                        - img
                      - 'cell "Welcome to CityLights Citylights is the new portal for visitors and residents. Find out what''s on, book tickets, and get the latest news. Heat wave linked to temperatures Man Gets Nine Months in Violin Case Lack of brains hinders research After three years of effort city scientists now agree that the primary cause of the 2003 heatwave was hot air from our Mayor: These kinds of crimes need more creative, effective punishments. For example, we could require compulsory Brain donations: huge drop off in brain donations due to the great ''success'' of ''Slow Traffic, Safe Streets'' policy Elsewhere on the Web Please see the following websites for important information. Citylights take no responsibility for their content. For artichoke advice, call the number below. bullet Killer bees. Click here. bullet Onions. Click here. Artichoke advice telephone hotline: 1234 56789"':
                        - paragraph: Welcome to CityLights
                        - paragraph: Citylights is the new portal for visitors and residents. Find out what's on, book tickets, and get the latest news.
                        - img
                        - link "Heat wave linked to temperatures":
                          - /url: news.html
                        - img
                        - link "Man Gets Nine Months in Violin Case":
                          - /url: news.html
                        - img
                        - link "Lack of brains hinders research":
                          - /url: news.html
                        - text: After three years of effort city scientists now agree that the primary cause of the 2003 heatwave was hot air from our
                        - link:
                          - /url: news.html
                        - text: "Mayor: These kinds of crimes need more creative, effective punishments. For example, we could require compulsory"
                        - link:
                          - /url: news.html
                        - text: "Brain donations: huge drop off in brain donations due to the great 'success' of 'Slow Traffic, Safe Streets' policy"
                        - link:
                          - /url: news.html
                        - paragraph: Elsewhere on the Web
                        - paragraph:
                          - text: Please see the following websites for important information. Citylights take no responsibility for their content. For artichoke advice, call the number below.
                          - img "bullet"
                          - text: Killer bees.
                          - link "Click here":
                            - /url: ../offsite.html
                          - text: .
                          - img "bullet"
                          - text: Onions.
                          - link "Click here":
                            - /url: ../offsite.html
                          - text: ". Artichoke advice telephone hotline:"
                          - img "1234 56789"
                      - cell:
                        - img
                      - cell "Free Penguins \"Free penguins\" slogan at zoo benefit concert causes confusion among city rockers. Adjective or verb? Read More... More City Parks More parks and more green throughout the city at the price of already rare car parking spaces, how will this affect you? Read More...":
                        - table:
                          - rowgroup:
                            - row:
                              - cell:
                                - img
                              - cell:
                                - img
                            - row "Free Penguins":
                              - cell "Free Penguins"
                            - row:
                              - cell:
                                - img
                            - row "\"Free penguins\" slogan at zoo benefit concert causes confusion among city rockers. Adjective or verb? Read More...":
                              - cell "\"Free penguins\" slogan at zoo benefit concert causes confusion among city rockers. Adjective or verb? Read More...":
                                - table:
                                  - rowgroup:
                                    - row "\"Free penguins\" slogan at zoo benefit concert causes confusion among city rockers. Adjective or verb? Read More...":
                                      - cell "\"Free penguins\" slogan at zoo benefit concert causes confusion among city rockers. Adjective or verb? Read More...":
                                        - text: "\"Free penguins\" slogan at zoo benefit concert causes confusion among city rockers. Adjective or verb?"
                                        - link "Read More...":
                                          - /url: tickets.html
                            - row:
                              - cell
                            - row:
                              - cell:
                                - img
                            - row "More City Parks":
                              - cell "More City Parks"
                            - row:
                              - cell:
                                - img
                            - row "More parks and more green throughout the city at the price of already rare car parking spaces, how will this affect you? Read More...":
                              - cell "More parks and more green throughout the city at the price of already rare car parking spaces, how will this affect you? Read More...":
                                - table:
                                  - rowgroup:
                                    - row "More parks and more green throughout the city at the price of already rare car parking spaces, how will this affect you? Read More...":
                                      - cell "More parks and more green throughout the city at the price of already rare car parking spaces, how will this affect you? Read More...":
                                        - text: More parks and more green throughout the city at the price of already rare car parking spaces, how will this affect you?
                                        - link "Read More...":
                                          - /url: survey.html
                - table:
                  - rowgroup:
                    - row "Copyright © 2012 W3C® (MIT, ERCIM, Keio)":
                      - cell "Copyright © 2012 W3C® (MIT, ERCIM, Keio)":
                        - link "Copyright":
                          - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
                        - text: © 2012
                        - link "W3C":
                          - /url: https://www.w3.org/
                        - superscript: ®
                        - text: (
                        - link "MIT":
                          - /url: http://www.csail.mit.edu/
                        - text: ","
                        - link "ERCIM":
                          - /url: http://www.ercim.org/
                        - text: ","
                        - link "Keio":
                          - /url: http://www.keio.ac.jp/
                        - text: )
              - cell:
                - img
            - row:
              - cell:
                - img
              - cell:
                - img
              - cell:
                - img
- separator
- paragraph:
  - strong: "Status:"
  - text: 20 February 2012 (see
  - link "changelog":
    - /url: ../changelog.html
  - text: ") Editors:"
  - link "Shadi Abou-Zahra":
    - /url: https://www.w3.org/People/shadi/
  - text: and the
  - link "Education and Outreach Working Group (EOWG)":
    - /url: https://www.w3.org/WAI/EO/
  - text: . Developed with support from
  - link "WAI-TIES":
    - /url: https://www.w3.org/WAI/TIES/
  - text: and
  - link "WAI-AGE":
    - /url: https://www.w3.org/WAI/WAI-AGE/
  - text: projects, co-funded by the European Commission IST Programme. [see
  - link "Acknowledgements":
    - /url: ../acks.html
  - text: "]"
- paragraph:
  - text: "["
  - link "WAI Site Map":
    - /url: https://www.w3.org/WAI/sitemap.html
  - text: "] ["
  - link "Help with WAI Website":
    - /url: https://www.w3.org/WAI/sitehelp.html
  - text: "] ["
  - link "Search":
    - /url: https://www.w3.org/WAI/search.php
  - text: "] ["
  - link "Contacting WAI":
    - /url: https://www.w3.org/WAI/contacts
  - text: "]"
  - strong:
    - text: Feedback welcome to
    - link "wai-eo-editors@w3.org":
      - /url: mailto:wai-eo-editors@w3.org
  - text: (a publicly archived list) or
  - link "wai@w3.org":
    - /url: mailto:wai@w3.org
  - text: (a WAI staff-only list).
- paragraph:
  - link "Copyright":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Copyright
  - text: © 2012
  - link "W3C":
    - /url: https://www.w3.org/
  - superscript: ®
  - text: (
  - link "MIT":
    - /url: http://www.csail.mit.edu/
  - text: ","
  - link "ERCIM":
    - /url: http://www.ercim.org/
  - text: ","
  - link "Keio":
    - /url: http://www.keio.ac.jp/
  - text: ), All Rights Reserved. W3C
  - link "liability":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#Legal_Disclaimer
  - text: ","
  - link "trademark":
    - /url: https://www.w3.org/Consortium/Legal/ipr-notice#W3C_Trademarks
  - text: ","
  - link "document use":
    - /url: https://www.w3.org/Consortium/Legal/copyright-documents
  - text: and
  - link "software licensing":
    - /url: https://www.w3.org/Consortium/Legal/copyright-software
  - text: rules apply. Your interactions with this site are in accordance with our
  - link "public":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Public
  - text: and
  - link "Member":
    - /url: https://www.w3.org/Consortium/Legal/privacy-statement#Members
  - text: privacy statements.