[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e29"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - text present \"Map Layers\"",
      "postcondition 2: passed - text present \"CyclOSM\""
    ]
  }
]
