[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e15"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - url contains \"/admin/admin/user/new/\"",
      "postcondition 2: passed - text present \"Heading level 1: New User\""
    ]
  },
  {
    "from": "s001",
    "action": {
      "type": "type",
      "target": "e24",
      "text": "lyra.quinn"
    },
    "to": "s002",
    "notes": []
  },
  {
    "from": "s002",
    "action": {
      "type": "type",
      "target": "e25",
      "text": "Lyra"
    },
    "to": "s003",
    "notes": []
  },
  {
    "from": "s003",
    "action": {
      "type": "type",
      "target": "e26",
      "text": "Quinn"
    },
    "to": "s004",
    "notes": []
  },
  {
    "from": "s004",
    "action": {
      "type": "type",
      "target": "e27",
      "text": "lyra.quinn@example.test"
    },
    "to": "s005",
    "notes": []
  },
  {
    "from": "s005",
    "action": {
      "type": "type",
      "target": "e28",
      "text": "NExUIUser!2026"
    },
    "to": "s006",
    "notes": []
  },
  {
    "from": "s006",
    "action": {
      "type": "type",
      "target": "e29",
      "text": "NExUIUser!2026"
    },
    "to": "s007",
    "notes": []
  },
  {
    "from": "s007",
    "action": {
      "type": "type",
      "target": "e33",
      "text": "admin1234"
    },
    "to": "s008",
    "notes": []
  },
  {
    "from": "s008",
    "action": {
      "type": "click",
      "target": "e19"
    },
    "to": "s009",
    "notes": [
      "postcondition 1: passed - text present \"Administrators\""
    ]
  },
  {
    "from": "s009",
    "action": {
      "type": "click",
      "target": "e32"
    },
    "to": "s010",
    "notes": [
      "postcondition 1: passed - candidate exists for {\"role\":\"radio\",\"value\":\"1\",\"states\":{\"checked\":true}}"
    ]
  },
  {
    "from": "s010",
    "action": {
      "type": "click",
      "target": "e18"
    },
    "to": "s011",
    "notes": [
      "postcondition 1: passed - field value equals \"lyra.quinn\""
    ]
  },
  {
    "from": "s011",
    "action": {
      "type": "click",
      "target": "e17"
    },
    "to": "s012",
    "notes": [
      "postcondition 1: passed - text present \"lyra.quinn\"",
      "postcondition 2: passed - text present \"lyra.quinn@example.test\""
    ]
  },
  {
    "from": "s012",
    "action": {
      "type": "click",
      "target": "e37"
    },
    "to": "s013",
    "notes": [
      "postcondition 1: passed - url contains \"/admin/admin/user/edit/user_id/\"",
      "postcondition 2: passed - field value equals \"lyra.quinn\"",
      "postcondition 3: passed - field value equals \"lyra.quinn@example.test\""
    ]
  },
  {
    "from": "s013",
    "action": {
      "type": "type",
      "target": "e25",
      "text": "Lyra Prime"
    },
    "to": "s014",
    "notes": []
  },
  {
    "from": "s014",
    "action": {
      "type": "type",
      "target": "e27",
      "text": "lyra.quinn+review@example.test"
    },
    "to": "s015",
    "notes": []
  },
  {
    "from": "s015",
    "action": {
      "type": "click",
      "target": "e38"
    },
    "to": "s016",
    "notes": [
      "postcondition 1: passed - candidate exists for {\"role\":\"radio\",\"value\":\"1\",\"states\":{\"checked\":true}}"
    ]
  },
  {
    "from": "s016",
    "action": {
      "type": "click",
      "target": "e36"
    },
    "to": "s017",
    "notes": [
      "postcondition 1: passed - field value equals \"Lyra Prime\"",
      "postcondition 2: passed - field value equals \"lyra.quinn+review@example.test\""
    ]
  }
]
