[
  {
    "from": "s000",
    "action": {
      "type": "click",
      "target": "e17"
    },
    "to": "s001",
    "notes": [
      "postcondition 1: passed - url contains \"/au/before.html\""
    ]
  }
]
